/* soapStub.h
   Generated by gSOAP 2.8.127 for operations.h

gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_NAMESPACE_OF_ns1	"http://www.example.org/operations/"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 208127
# error "GSOAP VERSION 208127 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

struct _ns1__storeFile;	/* operations.h:169 */
struct _ns1__storeFileResponse;	/* operations.h:185 */
struct _ns1__createFile;	/* operations.h:201 */
struct _ns1__createFileResponse;	/* operations.h:217 */
struct _ns1__modifyFile;	/* operations.h:233 */
struct _ns1__modifyFileResponse;	/* operations.h:249 */
struct _ns1__removeFile;	/* operations.h:265 */
struct _ns1__removeFileResponse;	/* operations.h:281 */
struct _ns1__store_USCOREexec_USCOREfile;	/* operations.h:297 */
struct _ns1__store_USCOREexec_USCOREfileResponse;	/* operations.h:313 */
struct _ns1__clientLogFiles;	/* operations.h:329 */
struct _ns1__NewOperationResponse;	/* operations.h:345 */
struct _ns1__clientLogFilesResponse1;	/* operations.h:361 */
struct _ns1__servFiles;	/* operations.h:377 */
struct _ns1__servFilesResponse1;	/* operations.h:393 */
struct _ns1__filesInCertainProgLanguage;	/* operations.h:409 */
struct _ns1__filesInCertainProgLanguageResponse1;	/* operations.h:425 */
struct _ns1__largestServFile;	/* operations.h:441 */
struct _ns1__largestServFileResponse1;	/* operations.h:457 */
struct _ns1__smallestServFile;	/* operations.h:473 */
struct _ns1__smallestServFileResponse1;	/* operations.h:489 */
struct _ns1__filesStatistics;	/* operations.h:505 */
struct _ns1__filesStatisticsResponse1;	/* operations.h:521 */
struct _ns1__totalServFilesSize;	/* operations.h:537 */
struct _ns1__totalServFilesSizeResponse1;	/* operations.h:553 */
struct __ns1__storeFile;	/* operations.h:706 */
struct __ns1__createFile;	/* operations.h:764 */
struct __ns1__modifyFile;	/* operations.h:822 */
struct __ns1__removeFile;	/* operations.h:880 */
struct __ns1__clientLogFiles;	/* operations.h:938 */
struct __ns1__servFiles;	/* operations.h:996 */
struct __ns1__filesInCertainProgLanguage;	/* operations.h:1054 */
struct __ns1__largestServFile;	/* operations.h:1112 */
struct __ns1__smallestServFile;	/* operations.h:1170 */
struct __ns1__filesStatistics;	/* operations.h:1228 */
struct __ns1__totalServFilesSize;	/* operations.h:1286 */

/* operations.h:169 */
#ifndef SOAP_TYPE__ns1__storeFile
#define SOAP_TYPE__ns1__storeFile (7)
/* complex XML schema type 'ns1:storeFile': */
struct _ns1__storeFile {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* operations.h:185 */
#ifndef SOAP_TYPE__ns1__storeFileResponse
#define SOAP_TYPE__ns1__storeFileResponse (8)
/* complex XML schema type 'ns1:storeFileResponse': */
struct _ns1__storeFileResponse {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* operations.h:201 */
#ifndef SOAP_TYPE__ns1__createFile
#define SOAP_TYPE__ns1__createFile (9)
/* complex XML schema type 'ns1:createFile': */
struct _ns1__createFile {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* operations.h:217 */
#ifndef SOAP_TYPE__ns1__createFileResponse
#define SOAP_TYPE__ns1__createFileResponse (10)
/* complex XML schema type 'ns1:createFileResponse': */
struct _ns1__createFileResponse {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* operations.h:233 */
#ifndef SOAP_TYPE__ns1__modifyFile
#define SOAP_TYPE__ns1__modifyFile (11)
/* complex XML schema type 'ns1:modifyFile': */
struct _ns1__modifyFile {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* operations.h:249 */
#ifndef SOAP_TYPE__ns1__modifyFileResponse
#define SOAP_TYPE__ns1__modifyFileResponse (12)
/* complex XML schema type 'ns1:modifyFileResponse': */
struct _ns1__modifyFileResponse {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* operations.h:265 */
#ifndef SOAP_TYPE__ns1__removeFile
#define SOAP_TYPE__ns1__removeFile (13)
/* complex XML schema type 'ns1:removeFile': */
struct _ns1__removeFile {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* operations.h:281 */
#ifndef SOAP_TYPE__ns1__removeFileResponse
#define SOAP_TYPE__ns1__removeFileResponse (14)
/* complex XML schema type 'ns1:removeFileResponse': */
struct _ns1__removeFileResponse {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* operations.h:297 */
#ifndef SOAP_TYPE__ns1__store_USCOREexec_USCOREfile
#define SOAP_TYPE__ns1__store_USCOREexec_USCOREfile (15)
/* complex XML schema type 'ns1:store_exec_file': */
struct _ns1__store_USCOREexec_USCOREfile {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* operations.h:313 */
#ifndef SOAP_TYPE__ns1__store_USCOREexec_USCOREfileResponse
#define SOAP_TYPE__ns1__store_USCOREexec_USCOREfileResponse (16)
/* complex XML schema type 'ns1:store_exec_fileResponse': */
struct _ns1__store_USCOREexec_USCOREfileResponse {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* operations.h:329 */
#ifndef SOAP_TYPE__ns1__clientLogFiles
#define SOAP_TYPE__ns1__clientLogFiles (17)
/* complex XML schema type 'ns1:clientLogFiles': */
struct _ns1__clientLogFiles {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* operations.h:345 */
#ifndef SOAP_TYPE__ns1__NewOperationResponse
#define SOAP_TYPE__ns1__NewOperationResponse (18)
/* complex XML schema type 'ns1:NewOperationResponse': */
struct _ns1__NewOperationResponse {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* operations.h:361 */
#ifndef SOAP_TYPE__ns1__clientLogFilesResponse1
#define SOAP_TYPE__ns1__clientLogFilesResponse1 (19)
/* complex XML schema type 'ns1:clientLogFilesResponse1': */
struct _ns1__clientLogFilesResponse1 {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* operations.h:377 */
#ifndef SOAP_TYPE__ns1__servFiles
#define SOAP_TYPE__ns1__servFiles (20)
/* complex XML schema type 'ns1:servFiles': */
struct _ns1__servFiles {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* operations.h:393 */
#ifndef SOAP_TYPE__ns1__servFilesResponse1
#define SOAP_TYPE__ns1__servFilesResponse1 (21)
/* complex XML schema type 'ns1:servFilesResponse1': */
struct _ns1__servFilesResponse1 {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* operations.h:409 */
#ifndef SOAP_TYPE__ns1__filesInCertainProgLanguage
#define SOAP_TYPE__ns1__filesInCertainProgLanguage (22)
/* complex XML schema type 'ns1:filesInCertainProgLanguage': */
struct _ns1__filesInCertainProgLanguage {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* operations.h:425 */
#ifndef SOAP_TYPE__ns1__filesInCertainProgLanguageResponse1
#define SOAP_TYPE__ns1__filesInCertainProgLanguageResponse1 (23)
/* complex XML schema type 'ns1:filesInCertainProgLanguageResponse1': */
struct _ns1__filesInCertainProgLanguageResponse1 {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* operations.h:441 */
#ifndef SOAP_TYPE__ns1__largestServFile
#define SOAP_TYPE__ns1__largestServFile (24)
/* complex XML schema type 'ns1:largestServFile': */
struct _ns1__largestServFile {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* operations.h:457 */
#ifndef SOAP_TYPE__ns1__largestServFileResponse1
#define SOAP_TYPE__ns1__largestServFileResponse1 (25)
/* complex XML schema type 'ns1:largestServFileResponse1': */
struct _ns1__largestServFileResponse1 {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* operations.h:473 */
#ifndef SOAP_TYPE__ns1__smallestServFile
#define SOAP_TYPE__ns1__smallestServFile (26)
/* complex XML schema type 'ns1:smallestServFile': */
struct _ns1__smallestServFile {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* operations.h:489 */
#ifndef SOAP_TYPE__ns1__smallestServFileResponse1
#define SOAP_TYPE__ns1__smallestServFileResponse1 (27)
/* complex XML schema type 'ns1:smallestServFileResponse1': */
struct _ns1__smallestServFileResponse1 {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* operations.h:505 */
#ifndef SOAP_TYPE__ns1__filesStatistics
#define SOAP_TYPE__ns1__filesStatistics (28)
/* complex XML schema type 'ns1:filesStatistics': */
struct _ns1__filesStatistics {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* operations.h:521 */
#ifndef SOAP_TYPE__ns1__filesStatisticsResponse1
#define SOAP_TYPE__ns1__filesStatisticsResponse1 (29)
/* complex XML schema type 'ns1:filesStatisticsResponse1': */
struct _ns1__filesStatisticsResponse1 {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* operations.h:537 */
#ifndef SOAP_TYPE__ns1__totalServFilesSize
#define SOAP_TYPE__ns1__totalServFilesSize (30)
/* complex XML schema type 'ns1:totalServFilesSize': */
struct _ns1__totalServFilesSize {
        /** Required element 'in' of XML schema type 'xsd:string' */
        char *in;
};
#endif

/* operations.h:553 */
#ifndef SOAP_TYPE__ns1__totalServFilesSizeResponse1
#define SOAP_TYPE__ns1__totalServFilesSizeResponse1 (31)
/* complex XML schema type 'ns1:totalServFilesSizeResponse1': */
struct _ns1__totalServFilesSizeResponse1 {
        /** Required element 'out' of XML schema type 'xsd:string' */
        char *out;
};
#endif

/* operations.h:706 */
#ifndef SOAP_TYPE___ns1__storeFile
#define SOAP_TYPE___ns1__storeFile (35)
/* Wrapper: */
struct __ns1__storeFile {
        /** Optional element 'ns1:storeFile' of XML schema type 'ns1:storeFile' */
        struct _ns1__storeFile *ns1__storeFile;
};
#endif

/* operations.h:764 */
#ifndef SOAP_TYPE___ns1__createFile
#define SOAP_TYPE___ns1__createFile (40)
/* Wrapper: */
struct __ns1__createFile {
        /** Context that manages this object */
        struct soap *s;
        /** Optional element 'ns1:createFile' of XML schema type 'ns1:createFile' */
        struct _ns1__createFile *ns1__createFile;
};
#endif

/* operations.h:822 */
#ifndef SOAP_TYPE___ns1__modifyFile
#define SOAP_TYPE___ns1__modifyFile (44)
/* Wrapper: */
struct __ns1__modifyFile {
        /** Optional element 'ns1:modifyFile' of XML schema type 'ns1:modifyFile' */
        struct _ns1__modifyFile *ns1__modifyFile;
};
#endif

/* operations.h:880 */
#ifndef SOAP_TYPE___ns1__removeFile
#define SOAP_TYPE___ns1__removeFile (48)
/* Wrapper: */
struct __ns1__removeFile {
        /** Optional element 'ns1:removeFile' of XML schema type 'ns1:removeFile' */
        struct _ns1__removeFile *ns1__removeFile;
};
#endif

/* operations.h:938 */
#ifndef SOAP_TYPE___ns1__clientLogFiles
#define SOAP_TYPE___ns1__clientLogFiles (52)
/* Wrapper: */
struct __ns1__clientLogFiles {
        /** Optional element 'ns1:clientLogFiles' of XML schema type 'ns1:clientLogFiles' */
        struct _ns1__clientLogFiles *ns1__clientLogFiles;
};
#endif

/* operations.h:996 */
#ifndef SOAP_TYPE___ns1__servFiles
#define SOAP_TYPE___ns1__servFiles (56)
/* Wrapper: */
struct __ns1__servFiles {
        /** Optional element 'ns1:servFiles' of XML schema type 'ns1:servFiles' */
        struct _ns1__servFiles *ns1__servFiles;
};
#endif

/* operations.h:1054 */
#ifndef SOAP_TYPE___ns1__filesInCertainProgLanguage
#define SOAP_TYPE___ns1__filesInCertainProgLanguage (60)
/* Wrapper: */
struct __ns1__filesInCertainProgLanguage {
        /** Optional element 'ns1:filesInCertainProgLanguage' of XML schema type 'ns1:filesInCertainProgLanguage' */
        struct _ns1__filesInCertainProgLanguage *ns1__filesInCertainProgLanguage;
};
#endif

/* operations.h:1112 */
#ifndef SOAP_TYPE___ns1__largestServFile
#define SOAP_TYPE___ns1__largestServFile (64)
/* Wrapper: */
struct __ns1__largestServFile {
        /** Optional element 'ns1:largestServFile' of XML schema type 'ns1:largestServFile' */
        struct _ns1__largestServFile *ns1__largestServFile;
};
#endif

/* operations.h:1170 */
#ifndef SOAP_TYPE___ns1__smallestServFile
#define SOAP_TYPE___ns1__smallestServFile (68)
/* Wrapper: */
struct __ns1__smallestServFile {
        /** Optional element 'ns1:smallestServFile' of XML schema type 'ns1:smallestServFile' */
        struct _ns1__smallestServFile *ns1__smallestServFile;
};
#endif

/* operations.h:1228 */
#ifndef SOAP_TYPE___ns1__filesStatistics
#define SOAP_TYPE___ns1__filesStatistics (72)
/* Wrapper: */
struct __ns1__filesStatistics {
        /** Optional element 'ns1:filesStatistics' of XML schema type 'ns1:filesStatistics' */
        struct _ns1__filesStatistics *ns1__filesStatistics;
};
#endif

/* operations.h:1286 */
#ifndef SOAP_TYPE___ns1__totalServFilesSize
#define SOAP_TYPE___ns1__totalServFilesSize (76)
/* Wrapper: */
struct __ns1__totalServFilesSize {
        /** Optional element 'ns1:totalServFilesSize' of XML schema type 'ns1:totalServFilesSize' */
        struct _ns1__totalServFilesSize *ns1__totalServFilesSize;
};
#endif

/* operations.h:1722 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (77)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif
#endif

/* operations.h:1722 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (78)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* operations.h:1722 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (80)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure through this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* operations.h:1722 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (83)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* operations.h:1722 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (84)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (84)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (83)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (80)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (78)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (77)
#endif

/* struct _ns1__totalServFilesSizeResponse1 has binding name '_ns1__totalServFilesSizeResponse1' for type '' */
#ifndef SOAP_TYPE__ns1__totalServFilesSizeResponse1
#define SOAP_TYPE__ns1__totalServFilesSizeResponse1 (31)
#endif

/* struct _ns1__totalServFilesSize has binding name '_ns1__totalServFilesSize' for type '' */
#ifndef SOAP_TYPE__ns1__totalServFilesSize
#define SOAP_TYPE__ns1__totalServFilesSize (30)
#endif

/* struct _ns1__filesStatisticsResponse1 has binding name '_ns1__filesStatisticsResponse1' for type '' */
#ifndef SOAP_TYPE__ns1__filesStatisticsResponse1
#define SOAP_TYPE__ns1__filesStatisticsResponse1 (29)
#endif

/* struct _ns1__filesStatistics has binding name '_ns1__filesStatistics' for type '' */
#ifndef SOAP_TYPE__ns1__filesStatistics
#define SOAP_TYPE__ns1__filesStatistics (28)
#endif

/* struct _ns1__smallestServFileResponse1 has binding name '_ns1__smallestServFileResponse1' for type '' */
#ifndef SOAP_TYPE__ns1__smallestServFileResponse1
#define SOAP_TYPE__ns1__smallestServFileResponse1 (27)
#endif

/* struct _ns1__smallestServFile has binding name '_ns1__smallestServFile' for type '' */
#ifndef SOAP_TYPE__ns1__smallestServFile
#define SOAP_TYPE__ns1__smallestServFile (26)
#endif

/* struct _ns1__largestServFileResponse1 has binding name '_ns1__largestServFileResponse1' for type '' */
#ifndef SOAP_TYPE__ns1__largestServFileResponse1
#define SOAP_TYPE__ns1__largestServFileResponse1 (25)
#endif

/* struct _ns1__largestServFile has binding name '_ns1__largestServFile' for type '' */
#ifndef SOAP_TYPE__ns1__largestServFile
#define SOAP_TYPE__ns1__largestServFile (24)
#endif

/* struct _ns1__filesInCertainProgLanguageResponse1 has binding name '_ns1__filesInCertainProgLanguageResponse1' for type '' */
#ifndef SOAP_TYPE__ns1__filesInCertainProgLanguageResponse1
#define SOAP_TYPE__ns1__filesInCertainProgLanguageResponse1 (23)
#endif

/* struct _ns1__filesInCertainProgLanguage has binding name '_ns1__filesInCertainProgLanguage' for type '' */
#ifndef SOAP_TYPE__ns1__filesInCertainProgLanguage
#define SOAP_TYPE__ns1__filesInCertainProgLanguage (22)
#endif

/* struct _ns1__servFilesResponse1 has binding name '_ns1__servFilesResponse1' for type '' */
#ifndef SOAP_TYPE__ns1__servFilesResponse1
#define SOAP_TYPE__ns1__servFilesResponse1 (21)
#endif

/* struct _ns1__servFiles has binding name '_ns1__servFiles' for type '' */
#ifndef SOAP_TYPE__ns1__servFiles
#define SOAP_TYPE__ns1__servFiles (20)
#endif

/* struct _ns1__clientLogFilesResponse1 has binding name '_ns1__clientLogFilesResponse1' for type '' */
#ifndef SOAP_TYPE__ns1__clientLogFilesResponse1
#define SOAP_TYPE__ns1__clientLogFilesResponse1 (19)
#endif

/* struct _ns1__NewOperationResponse has binding name '_ns1__NewOperationResponse' for type '' */
#ifndef SOAP_TYPE__ns1__NewOperationResponse
#define SOAP_TYPE__ns1__NewOperationResponse (18)
#endif

/* struct _ns1__clientLogFiles has binding name '_ns1__clientLogFiles' for type '' */
#ifndef SOAP_TYPE__ns1__clientLogFiles
#define SOAP_TYPE__ns1__clientLogFiles (17)
#endif

/* struct _ns1__store_USCOREexec_USCOREfileResponse has binding name '_ns1__store_USCOREexec_USCOREfileResponse' for type '' */
#ifndef SOAP_TYPE__ns1__store_USCOREexec_USCOREfileResponse
#define SOAP_TYPE__ns1__store_USCOREexec_USCOREfileResponse (16)
#endif

/* struct _ns1__store_USCOREexec_USCOREfile has binding name '_ns1__store_USCOREexec_USCOREfile' for type '' */
#ifndef SOAP_TYPE__ns1__store_USCOREexec_USCOREfile
#define SOAP_TYPE__ns1__store_USCOREexec_USCOREfile (15)
#endif

/* struct _ns1__removeFileResponse has binding name '_ns1__removeFileResponse' for type '' */
#ifndef SOAP_TYPE__ns1__removeFileResponse
#define SOAP_TYPE__ns1__removeFileResponse (14)
#endif

/* struct _ns1__removeFile has binding name '_ns1__removeFile' for type '' */
#ifndef SOAP_TYPE__ns1__removeFile
#define SOAP_TYPE__ns1__removeFile (13)
#endif

/* struct _ns1__modifyFileResponse has binding name '_ns1__modifyFileResponse' for type '' */
#ifndef SOAP_TYPE__ns1__modifyFileResponse
#define SOAP_TYPE__ns1__modifyFileResponse (12)
#endif

/* struct _ns1__modifyFile has binding name '_ns1__modifyFile' for type '' */
#ifndef SOAP_TYPE__ns1__modifyFile
#define SOAP_TYPE__ns1__modifyFile (11)
#endif

/* struct _ns1__createFileResponse has binding name '_ns1__createFileResponse' for type '' */
#ifndef SOAP_TYPE__ns1__createFileResponse
#define SOAP_TYPE__ns1__createFileResponse (10)
#endif

/* struct _ns1__createFile has binding name '_ns1__createFile' for type '' */
#ifndef SOAP_TYPE__ns1__createFile
#define SOAP_TYPE__ns1__createFile (9)
#endif

/* struct _ns1__storeFileResponse has binding name '_ns1__storeFileResponse' for type '' */
#ifndef SOAP_TYPE__ns1__storeFileResponse
#define SOAP_TYPE__ns1__storeFileResponse (8)
#endif

/* struct _ns1__storeFile has binding name '_ns1__storeFile' for type '' */
#ifndef SOAP_TYPE__ns1__storeFile
#define SOAP_TYPE__ns1__storeFile (7)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (86)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (85)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (79)
#endif

/* struct _ns1__totalServFilesSizeResponse1 * has binding name 'PointerTo_ns1__totalServFilesSizeResponse1' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__totalServFilesSizeResponse1
#define SOAP_TYPE_PointerTo_ns1__totalServFilesSizeResponse1 (74)
#endif

/* struct _ns1__totalServFilesSize * has binding name 'PointerTo_ns1__totalServFilesSize' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__totalServFilesSize
#define SOAP_TYPE_PointerTo_ns1__totalServFilesSize (73)
#endif

/* struct _ns1__filesStatisticsResponse1 * has binding name 'PointerTo_ns1__filesStatisticsResponse1' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__filesStatisticsResponse1
#define SOAP_TYPE_PointerTo_ns1__filesStatisticsResponse1 (70)
#endif

/* struct _ns1__filesStatistics * has binding name 'PointerTo_ns1__filesStatistics' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__filesStatistics
#define SOAP_TYPE_PointerTo_ns1__filesStatistics (69)
#endif

/* struct _ns1__smallestServFileResponse1 * has binding name 'PointerTo_ns1__smallestServFileResponse1' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__smallestServFileResponse1
#define SOAP_TYPE_PointerTo_ns1__smallestServFileResponse1 (66)
#endif

/* struct _ns1__smallestServFile * has binding name 'PointerTo_ns1__smallestServFile' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__smallestServFile
#define SOAP_TYPE_PointerTo_ns1__smallestServFile (65)
#endif

/* struct _ns1__largestServFileResponse1 * has binding name 'PointerTo_ns1__largestServFileResponse1' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__largestServFileResponse1
#define SOAP_TYPE_PointerTo_ns1__largestServFileResponse1 (62)
#endif

/* struct _ns1__largestServFile * has binding name 'PointerTo_ns1__largestServFile' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__largestServFile
#define SOAP_TYPE_PointerTo_ns1__largestServFile (61)
#endif

/* struct _ns1__filesInCertainProgLanguageResponse1 * has binding name 'PointerTo_ns1__filesInCertainProgLanguageResponse1' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__filesInCertainProgLanguageResponse1
#define SOAP_TYPE_PointerTo_ns1__filesInCertainProgLanguageResponse1 (58)
#endif

/* struct _ns1__filesInCertainProgLanguage * has binding name 'PointerTo_ns1__filesInCertainProgLanguage' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__filesInCertainProgLanguage
#define SOAP_TYPE_PointerTo_ns1__filesInCertainProgLanguage (57)
#endif

/* struct _ns1__servFilesResponse1 * has binding name 'PointerTo_ns1__servFilesResponse1' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__servFilesResponse1
#define SOAP_TYPE_PointerTo_ns1__servFilesResponse1 (54)
#endif

/* struct _ns1__servFiles * has binding name 'PointerTo_ns1__servFiles' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__servFiles
#define SOAP_TYPE_PointerTo_ns1__servFiles (53)
#endif

/* struct _ns1__clientLogFilesResponse1 * has binding name 'PointerTo_ns1__clientLogFilesResponse1' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__clientLogFilesResponse1
#define SOAP_TYPE_PointerTo_ns1__clientLogFilesResponse1 (50)
#endif

/* struct _ns1__clientLogFiles * has binding name 'PointerTo_ns1__clientLogFiles' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__clientLogFiles
#define SOAP_TYPE_PointerTo_ns1__clientLogFiles (49)
#endif

/* struct _ns1__removeFileResponse * has binding name 'PointerTo_ns1__removeFileResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__removeFileResponse
#define SOAP_TYPE_PointerTo_ns1__removeFileResponse (46)
#endif

/* struct _ns1__removeFile * has binding name 'PointerTo_ns1__removeFile' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__removeFile
#define SOAP_TYPE_PointerTo_ns1__removeFile (45)
#endif

/* struct _ns1__modifyFileResponse * has binding name 'PointerTo_ns1__modifyFileResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__modifyFileResponse
#define SOAP_TYPE_PointerTo_ns1__modifyFileResponse (42)
#endif

/* struct _ns1__modifyFile * has binding name 'PointerTo_ns1__modifyFile' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__modifyFile
#define SOAP_TYPE_PointerTo_ns1__modifyFile (41)
#endif

/* struct _ns1__createFileResponse * has binding name 'PointerTo_ns1__createFileResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__createFileResponse
#define SOAP_TYPE_PointerTo_ns1__createFileResponse (38)
#endif

/* struct _ns1__createFile * has binding name 'PointerTo_ns1__createFile' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__createFile
#define SOAP_TYPE_PointerTo_ns1__createFile (37)
#endif

/* struct _ns1__storeFileResponse * has binding name 'PointerTo_ns1__storeFileResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__storeFileResponse
#define SOAP_TYPE_PointerTo_ns1__storeFileResponse (33)
#endif

/* struct _ns1__storeFile * has binding name 'PointerTo_ns1__storeFile' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__storeFile
#define SOAP_TYPE_PointerTo_ns1__storeFile (32)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    
    /** Web service synchronous operation 'soap_call___ns1__storeFile' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__storeFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__storeFile *ns1__storeFile, struct _ns1__storeFileResponse *ns1__storeFileResponse);
    /** Web service asynchronous operation 'soap_send___ns1__storeFile' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__storeFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__storeFile *ns1__storeFile);
    /** Web service asynchronous operation 'soap_recv___ns1__storeFile' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__storeFile(struct soap *soap, struct _ns1__storeFileResponse *ns1__storeFileResponse);
    
    /** Web service synchronous operation 'soap_call___ns1__createFile' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__createFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soap *s, struct _ns1__createFile *ns1__createFile, struct _ns1__createFileResponse *ns1__createFileResponse);
    /** Web service asynchronous operation 'soap_send___ns1__createFile' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__createFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soap *s, struct _ns1__createFile *ns1__createFile);
    /** Web service asynchronous operation 'soap_recv___ns1__createFile' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__createFile(struct soap *soap, struct _ns1__createFileResponse *ns1__createFileResponse);
    
    /** Web service synchronous operation 'soap_call___ns1__modifyFile' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__modifyFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__modifyFile *ns1__modifyFile, struct _ns1__modifyFileResponse *ns1__modifyFileResponse);
    /** Web service asynchronous operation 'soap_send___ns1__modifyFile' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__modifyFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__modifyFile *ns1__modifyFile);
    /** Web service asynchronous operation 'soap_recv___ns1__modifyFile' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__modifyFile(struct soap *soap, struct _ns1__modifyFileResponse *ns1__modifyFileResponse);
    
    /** Web service synchronous operation 'soap_call___ns1__removeFile' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__removeFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__removeFile *ns1__removeFile, struct _ns1__removeFileResponse *ns1__removeFileResponse);
    /** Web service asynchronous operation 'soap_send___ns1__removeFile' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__removeFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__removeFile *ns1__removeFile);
    /** Web service asynchronous operation 'soap_recv___ns1__removeFile' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__removeFile(struct soap *soap, struct _ns1__removeFileResponse *ns1__removeFileResponse);
    
    /** Web service synchronous operation 'soap_call___ns1__clientLogFiles' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__clientLogFiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__clientLogFiles *ns1__clientLogFiles, struct _ns1__clientLogFilesResponse1 *ns1__clientLogFilesResponse1);
    /** Web service asynchronous operation 'soap_send___ns1__clientLogFiles' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__clientLogFiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__clientLogFiles *ns1__clientLogFiles);
    /** Web service asynchronous operation 'soap_recv___ns1__clientLogFiles' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__clientLogFiles(struct soap *soap, struct _ns1__clientLogFilesResponse1 *ns1__clientLogFilesResponse1);
    
    /** Web service synchronous operation 'soap_call___ns1__servFiles' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__servFiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__servFiles *ns1__servFiles, struct _ns1__servFilesResponse1 *ns1__servFilesResponse1);
    /** Web service asynchronous operation 'soap_send___ns1__servFiles' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__servFiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__servFiles *ns1__servFiles);
    /** Web service asynchronous operation 'soap_recv___ns1__servFiles' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__servFiles(struct soap *soap, struct _ns1__servFilesResponse1 *ns1__servFilesResponse1);
    
    /** Web service synchronous operation 'soap_call___ns1__filesInCertainProgLanguage' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__filesInCertainProgLanguage(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__filesInCertainProgLanguage *ns1__filesInCertainProgLanguage, struct _ns1__filesInCertainProgLanguageResponse1 *ns1__filesInCertainProgLanguageResponse1);
    /** Web service asynchronous operation 'soap_send___ns1__filesInCertainProgLanguage' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__filesInCertainProgLanguage(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__filesInCertainProgLanguage *ns1__filesInCertainProgLanguage);
    /** Web service asynchronous operation 'soap_recv___ns1__filesInCertainProgLanguage' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__filesInCertainProgLanguage(struct soap *soap, struct _ns1__filesInCertainProgLanguageResponse1 *ns1__filesInCertainProgLanguageResponse1);
    
    /** Web service synchronous operation 'soap_call___ns1__largestServFile' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__largestServFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__largestServFile *ns1__largestServFile, struct _ns1__largestServFileResponse1 *ns1__largestServFileResponse1);
    /** Web service asynchronous operation 'soap_send___ns1__largestServFile' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__largestServFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__largestServFile *ns1__largestServFile);
    /** Web service asynchronous operation 'soap_recv___ns1__largestServFile' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__largestServFile(struct soap *soap, struct _ns1__largestServFileResponse1 *ns1__largestServFileResponse1);
    
    /** Web service synchronous operation 'soap_call___ns1__smallestServFile' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__smallestServFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__smallestServFile *ns1__smallestServFile, struct _ns1__smallestServFileResponse1 *ns1__smallestServFileResponse1);
    /** Web service asynchronous operation 'soap_send___ns1__smallestServFile' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__smallestServFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__smallestServFile *ns1__smallestServFile);
    /** Web service asynchronous operation 'soap_recv___ns1__smallestServFile' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__smallestServFile(struct soap *soap, struct _ns1__smallestServFileResponse1 *ns1__smallestServFileResponse1);
    
    /** Web service synchronous operation 'soap_call___ns1__filesStatistics' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__filesStatistics(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__filesStatistics *ns1__filesStatistics, struct _ns1__filesStatisticsResponse1 *ns1__filesStatisticsResponse1);
    /** Web service asynchronous operation 'soap_send___ns1__filesStatistics' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__filesStatistics(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__filesStatistics *ns1__filesStatistics);
    /** Web service asynchronous operation 'soap_recv___ns1__filesStatistics' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__filesStatistics(struct soap *soap, struct _ns1__filesStatisticsResponse1 *ns1__filesStatisticsResponse1);
    
    /** Web service synchronous operation 'soap_call___ns1__totalServFilesSize' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__totalServFilesSize(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__totalServFilesSize *ns1__totalServFilesSize, struct _ns1__totalServFilesSizeResponse1 *ns1__totalServFilesSizeResponse1);
    /** Web service asynchronous operation 'soap_send___ns1__totalServFilesSize' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__totalServFilesSize(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__totalServFilesSize *ns1__totalServFilesSize);
    /** Web service asynchronous operation 'soap_recv___ns1__totalServFilesSize' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__totalServFilesSize(struct soap *soap, struct _ns1__totalServFilesSizeResponse1 *ns1__totalServFilesSizeResponse1);

/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/

    /** Web service operation '__ns1__storeFile' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__storeFile( struct soap*, struct _ns1__storeFile *ns1__storeFile, struct _ns1__storeFileResponse *ns1__storeFileResponse);
    /** Web service operation '__ns1__createFile' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__createFile(struct soap*, struct _ns1__createFile *ns1__createFile, struct _ns1__createFileResponse *ns1__createFileResponse);
    /** Web service operation '__ns1__modifyFile' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__modifyFile(struct soap*, struct _ns1__modifyFile *ns1__modifyFile, struct _ns1__modifyFileResponse *ns1__modifyFileResponse);
    /** Web service operation '__ns1__removeFile' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__removeFile(struct soap*, struct _ns1__removeFile *ns1__removeFile, struct _ns1__removeFileResponse *ns1__removeFileResponse);
    /** Web service operation '__ns1__clientLogFiles' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__clientLogFiles(struct soap*, struct _ns1__clientLogFiles *ns1__clientLogFiles, struct _ns1__clientLogFilesResponse1 *ns1__clientLogFilesResponse1);
    /** Web service operation '__ns1__servFiles' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__servFiles(struct soap*, struct _ns1__servFiles *ns1__servFiles, struct _ns1__servFilesResponse1 *ns1__servFilesResponse1);
    /** Web service operation '__ns1__filesInCertainProgLanguage' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__filesInCertainProgLanguage(struct soap*, struct _ns1__filesInCertainProgLanguage *ns1__filesInCertainProgLanguage, struct _ns1__filesInCertainProgLanguageResponse1 *ns1__filesInCertainProgLanguageResponse1);
    /** Web service operation '__ns1__largestServFile' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__largestServFile(struct soap*, struct _ns1__largestServFile *ns1__largestServFile, struct _ns1__largestServFileResponse1 *ns1__largestServFileResponse1);
    /** Web service operation '__ns1__smallestServFile' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__smallestServFile(struct soap*, struct _ns1__smallestServFile *ns1__smallestServFile, struct _ns1__smallestServFileResponse1 *ns1__smallestServFileResponse1);
    /** Web service operation '__ns1__filesStatistics' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__filesStatistics(struct soap*, struct _ns1__filesStatistics *ns1__filesStatistics, struct _ns1__filesStatisticsResponse1 *ns1__filesStatisticsResponse1);
    /** Web service operation '__ns1__totalServFilesSize' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__totalServFilesSize(struct soap*, struct _ns1__totalServFilesSize *ns1__totalServFilesSize, struct _ns1__totalServFilesSizeResponse1 *ns1__totalServFilesSizeResponse1);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__storeFile(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__createFile(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__modifyFile(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__removeFile(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__clientLogFiles(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__servFiles(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__filesInCertainProgLanguage(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__largestServFile(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__smallestServFile(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__filesStatistics(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__totalServFilesSize(struct soap*);

#endif

/* End of soapStub.h */
